[package]
name = "manager_derive_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.82"
quote = "1.0.10"
proc-macro2 = "1.0.33"

[dev-dependencies]
nft_models = { path = "../nft_models" }