[package]
name = "nft_models"
version = "0.1.0"
edition = "2021"

[dependencies]
near-contract-standards = "4.0.0-pre.4"
near-sdk = "4.0.0-pre.4"
enum_dispatch = "0.3.7"
slots_derive_macro = { path = "../slots_derive_macro" }