[package]
name = "nft_market"
version = "0.1.0"
authors = ["fomotoshi <fomotoshi@ya.ru>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "4.0.0-pre.4"
near-contract-standards = "4.0.0-pre.4"
token_metadata_ext = { path = "../token_metadata_ext" }

[dev-dependencies]
near-sdk-sim = "4.0.0-pre.4"
nft_token = { path = "../nft_token" }
spoiled_nft_token = { path = "../spoiled_nft_token" }
test_utils = { path = "../test_utils" }
