name: near-build-and-deploy

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: "wasm32-unknown-unknown"
          default: true
          override: true

      - name: near-toolchain
        run: npm install -g near-cli

      - name: build
        run: cargo build --all --release --target wasm32-unknown-unknown

      - name: tests
        run: cargo test

      - name: deploy NFT
        run: ./dev_nft_deploy.sh

      - name: echo dev credentials
        run: "source ./neardev/dev-account.env \
        && export MARKET=market.$CONTRACT_NAME \
        && echo nft contract: $CONTRACT_NAME \
        && echo market contract: $MARKET"