name: near-build-and-deploy

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: "wasm32-unknown-unknown"
          default: true
          override: true

      - name: near-toolchain
        run: npm install -g near-cli

      - name: build
        run: cargo build --release --target wasm32-unknown-unknown
# todo: return test invocation for ci
#      - name: tests
#        run: cargo test
